//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmenler
    {
        public int ogretmen_id { get; set; }
        public string ogretmen_adi { get; set; }
        public string ogretmen_soyadi { get; set; }
        public string ogretmen_posta { get; set; }
        public string ogretmen_telNo { get; set; }
        public string ogretmen_alan { get; set; }
    }
}
