//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        public int ogrenci_id { get; set; }
        public string ogrenci_adi { get; set; }
        public string ogrenci_soyadi { get; set; }
        public Nullable<int> ogrenci_numara { get; set; }
        public string ogrenci_posta { get; set; }
        public string ogrenci_telNo { get; set; }
        public string ogrenci_sinif { get; set; }
    }
}
